name: Security Review (Diff)

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: "Optional pull request number to review"
        required: false
        default: ""
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #     - reopened
  #     - ready_for_review
  #     - labeled

concurrency:
  group: security-review-diff-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-security-review:
    name: Pull Request Security Review
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      pull-requests: write
      issues: write

    env:
      SECURITY_BLOCK_LABEL: "security:blocked"
      SECURITY_RISK_LABEL_PREFIX: "security:risk:"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve comparison commits
        id: revision
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          base_sha="${{ github.event.pull_request.base.sha }}"
          head_sha="${{ github.sha }}"

          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.pull_request_number }}" ]; then
            pr_json=$(gh pr view "${{ github.event.inputs.pull_request_number }}" --json baseRefOid,headRefOid)
            base_sha=$(echo "$pr_json" | jq -r '.baseRefOid')
            head_sha=$(echo "$pr_json" | jq -r '.headRefOid')
          fi

          if [ -n "$base_sha" ]; then
            echo "base=$base_sha" >> "$GITHUB_OUTPUT"
          fi
          if [ -n "$head_sha" ]; then
            echo "head=$head_sha" >> "$GITHUB_OUTPUT"
          fi

      - name: Collect updated pin targets
        id: pins
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ steps.revision.outputs.base }}
          HEAD_SHA: ${{ steps.revision.outputs.head }}
        run: |
          set -euo pipefail
          base_sha="$BASE_SHA"
          head_sha="$HEAD_SHA"

          if [ -z "$base_sha" ] || [ -z "$head_sha" ]; then
            echo "has_targets=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          task ci -- collect-updated-pins \
            --base "$base_sha" \
            --head "$head_sha" \
            --workspace "${{ github.workspace }}" \
            --output-json pins-context.json \
            --summary-md pins-summary.md

          if [ -s pins-context.json ]; then
            echo "has_targets=true" >> "$GITHUB_OUTPUT"
            echo "context=pins-context.json" >> "$GITHUB_OUTPUT"
            echo "summary=pins-summary.md" >> "$GITHUB_OUTPUT"
          else
            echo "has_targets=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Collect new local servers
        id: newservers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ steps.revision.outputs.base }}
          HEAD_SHA: ${{ steps.revision.outputs.head }}
        run: |
          set -euo pipefail
          base_sha="$BASE_SHA"
          head_sha="$HEAD_SHA"

          if [ -z "$base_sha" ] || [ -z "$head_sha" ]; then
            echo "has_targets=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          task ci -- collect-new-servers \
            --base "$base_sha" \
            --head "$head_sha" \
            --workspace "${{ github.workspace }}" \
            --output-json new-servers-context.json \
            --summary-md new-servers-summary.md

          if [ -s new-servers-context.json ]; then
            echo "has_targets=true" >> "$GITHUB_OUTPUT"
            echo "context=new-servers-context.json" >> "$GITHUB_OUTPUT"
            echo "summary=new-servers-summary.md" >> "$GITHUB_OUTPUT"
          else
            echo "has_targets=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Ensure security labels exist
        if: steps.pins.outputs.has_targets == 'true' || steps.newservers.outputs.has_targets == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          gh label create "${SECURITY_BLOCK_LABEL}" \
            --color B60205 \
            --description "Security automation detected blocking issues." \
            || echo "Label ${SECURITY_BLOCK_LABEL} already exists."

          for risk in critical high medium low info; do
            label="${SECURITY_RISK_LABEL_PREFIX}${risk}"
            gh label create "$label" \
              --color 0E8A16 \
              --description "Security automation risk assessment: ${risk}." \
              || echo "Label $label already exists."
          done

      - name: Remove stale security labels
        if: steps.pins.outputs.has_targets == 'true' || steps.newservers.outputs.has_targets == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          for label in "${SECURITY_BLOCK_LABEL}" \
            "${SECURITY_RISK_LABEL_PREFIX}critical" \
            "${SECURITY_RISK_LABEL_PREFIX}high" \
            "${SECURITY_RISK_LABEL_PREFIX}medium" \
            "${SECURITY_RISK_LABEL_PREFIX}low" \
            "${SECURITY_RISK_LABEL_PREFIX}info"; do
            gh pr edit "${{ github.event.pull_request.number }}" \
              --repo "${{ github.repository }}" \
              --remove-label "$label" || true
          done

      - name: Prepare review context
        if: steps.pins.outputs.has_targets == 'true' || steps.newservers.outputs.has_targets == 'true'
        run: |
          set -euo pipefail
          mkdir -p /tmp/security-review/pins /tmp/security-review/new

          if [ "${{ steps.pins.outputs.has_targets }}" = "true" ]; then
            task ci -- prepare-updated-pins \
              --context-file "${{ steps.pins.outputs.context }}" \
              --output-dir /tmp/security-review/pins
          fi

          if [ "${{ steps.newservers.outputs.has_targets }}" = "true" ]; then
            task ci -- prepare-new-servers \
              --context-file "${{ steps.newservers.outputs.context }}" \
              --output-dir /tmp/security-review/new
          fi

          task ci -- compose-pr-summary \
            --pins-summary "${{ steps.pins.outputs.summary }}" \
            --new-summary "${{ steps.newservers.outputs.summary }}" \
            --output summary.md

      - name: Run security reviewer (Claude)
        if: steps.pins.outputs.has_targets == 'true' || steps.newservers.outputs.has_targets == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BASE_SHA: ${{ steps.revision.outputs.base }}
          HEAD_SHA: ${{ steps.revision.outputs.head }}
        run: |
          set -euo pipefail
          INPUT_ROOT="${RUNNER_TEMP}/reviewer/input"
          OUTPUT_ROOT="${RUNNER_TEMP}/reviewer/output"
          mkdir -p "$INPUT_ROOT" "$OUTPUT_ROOT"
          cp "${{ github.workspace }}/summary.md" "$INPUT_ROOT/summary.md"

          if [ -d /tmp/security-review ]; then
            mkdir -p "$INPUT_ROOT/contexts"
            cp -R /tmp/security-review/. "$INPUT_ROOT/contexts"
            export REVIEW_EXTRA_ALLOWED_DIRS="/input/contexts/pins /input/contexts/new"
          fi

          pushd agents/security-reviewer >/dev/null
          export REVIEW_INPUT_PATH="$INPUT_ROOT"
          export REVIEW_OUTPUT_PATH_HOST="$OUTPUT_ROOT"
          export REVIEW_SUMMARY_PATH="/input/summary.md"
          export REVIEW_MODE="diff"
          export REVIEW_HEAD_SHA="$HEAD_SHA"
          export REVIEW_BASE_SHA="$BASE_SHA"
          export REVIEW_TARGET_LABEL="PR-${{ github.event.pull_request.number || github.run_id }}"
          export REVIEW_AGENT="claude"
          cleanup() { docker compose down --volumes --remove-orphans || true; }
          trap cleanup EXIT
          docker compose up --build --abort-on-container-exit reviewer
          popd >/dev/null

          mkdir -p "${{ github.workspace }}/review-output"
          cp "$OUTPUT_ROOT/security-review.md" "${{ github.workspace }}/review-output/security-review.md"

      - name: Post security review as PR comment
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          if [ ! -f "${{ github.workspace }}/review-output/security-review.md" ]; then
            echo "No security review report produced."
            exit 0
          fi

          {
            cat "${{ github.workspace }}/review-output/security-review.md"
            echo ""
            echo "<!-- automated-security-review -->"
          } > security-review-comment.md

          comment_id=$(gh api \
            repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            --jq '.[] | select(.body | contains("<!-- automated-security-review -->")) | .id' \
            || true)

          if [ -n "$comment_id" ]; then
            gh api \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/issues/comments/$comment_id \
              -F body=@security-review-comment.md
          else
            gh pr comment ${{ github.event.pull_request.number }} \
              --repo ${{ github.repository }} \
              --body-file security-review-comment.md
          fi
